name: audiotags
description: Read and write audio metadata in Flutter. Supports multiple formats.
version: 1.4.5
homepage: https://github.com/erikas-taroza/audiotags
repository: https://github.com/erikas-taroza/audiotags

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.0.1
  flutter_rust_bridge: 2.10.0
  meta: ^1.8.0
  uuid: any
  freezed_annotation: ^3.0.0
  rust_lib_audiotags:
    path: rust_builder

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ffigen: ^9.0.1
  build_runner: ^2.4.6
  freezed: ^3.0.0
  analyzer: ">=7.5.9 <9.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.erikas.audiotags
        pluginClass: AudiotagsPlugin
      ios:
        pluginClass: AudiotagsPlugin
      linux:
        pluginClass: AudiotagsPlugin
      macos:
        pluginClass: AudiotagsPlugin
      windows:
        pluginClass: AudiotagsPluginCApi
